<template>
  <div class="record-create-form">
    <form @submit.prevent="createRecord" class="create-form">
      <div class="form-header">
        <h3>Create New {{ table?.displayName?.slice(0, -1) || 'Record' }}</h3>
        <p class="form-description">
          Fill in the details to create a new {{ table?.displayName?.toLowerCase() || 'record' }}.
        </p>
      </div>

      <div class="form-fields">
        <div v-for="field in requiredFields" :key="field.key" class="field-row">
          <label class="field-label">
            {{ field.label }}
            <span v-if="field.required" class="required">*</span>
          </label>
          <div class="field-input">
            <input
              v-if="field.type === 'text' || field.type === 'email'"
              v-model="formData[field.key]"
              :type="field.type"
              class="input-field"
              :class="{ error: errors[field.key] }"
              :placeholder="field.placeholder"
              :required="field.required"
            />
            <input
              v-else-if="field.type === 'number' || field.type === 'currency'"
              v-model.number="formData[field.key]"
              type="number"
              step="0.01"
              class="input-field"
              :class="{ error: errors[field.key] }"
              :placeholder="field.placeholder"
              :required="field.required"
            />
            <select
              v-else-if="field.type === 'select'"
              v-model="formData[field.key]"
              class="input-field"
              :class="{ error: errors[field.key] }"
              :required="field.required"
            >
              <option value="">{{ field.placeholder }}</option>
              <option v-for="option in field.options" :key="option" :value="option">
                {{ option }}
              </option>
            </select>
            <textarea
              v-else-if="field.type === 'textarea'"
              v-model="formData[field.key]"
              class="input-field textarea-field"
              :class="{ error: errors[field.key] }"
              :placeholder="field.placeholder"
              :required="field.required"
              rows="4"
            ></textarea>
            <input
              v-else
              v-model="formData[field.key]"
              type="text"
              class="input-field"
              :class="{ error: errors[field.key] }"
              :placeholder="field.placeholder"
              :required="field.required"
            />
          </div>
          <div v-if="errors[field.key]" class="error-message">
            {{ errors[field.key] }}
          </div>
        </div>
      </div>

      <div class="form-actions">
        <button type="button" @click="cancelCreate" class="btn btn-secondary">Cancel</button>
        <button type="submit" class="btn btn-primary" :disabled="creating">
          <span v-if="creating" class="loading-spinner"></span>
          Create {{ table?.displayName?.slice(0, -1) || 'Record' }}
        </button>
      </div>
    </form>
  </div>
</template>

<script>
import { ref, computed, onMounted } from 'vue'

export default {
  name: 'RecordCreateForm',
  props: {
    table: {
      type: Object,
      required: true,
    },
  },
  emits: ['save', 'cancel'],
  setup(props, { emit }) {
    const formData = ref({})
    const errors = ref({})
    const creating = ref(false)

    // Computed properties
    const requiredFields = computed(() => {
      return props.table.columns
        .filter((col) => {
          // Don't include auto-generated fields
          const autoGeneratedFields = ['id', 'created_at', 'updated_at']
          return !autoGeneratedFields.includes(col.key)
        })
        .map((field) => ({
          ...field,
          options: getFieldOptions(field.key),
          placeholder: getFieldPlaceholder(field.key),
          required: isFieldRequired(field.key),
        }))
    })

    // Methods
    const getFieldOptions = (fieldKey) => {
      const optionMappings = {
        type: ['deposit', 'withdrawal', 'payment', 'refund'],
        status: props.table.statusOptions || ['pending', 'completed', 'failed', 'cancelled'],
        payment_method: ['gcash', 'maya', 'bpi', 'bdo'],
        currency: ['PHP', 'USD'],
        role: ['user', 'developer', 'verifier', 'admin'],
      }
      return optionMappings[fieldKey] || []
    }

    const getFieldPlaceholder = (fieldKey) => {
      const placeholderMappings = {
        user_id: 'Enter user ID',
        amount: 'Enter amount',
        description: 'Enter description',
        full_name: 'Enter full name',
        email: 'Enter email address',
        title: 'Enter title',
        location: 'Enter location',
        methodology: 'Enter methodology',
        price: 'Enter price',
        available_credits: 'Enter available credits',
        comments: 'Enter comments',
        verification_notes: 'Enter verification notes',
        project_id: 'Enter project ID',
        verifier_id: 'Enter verifier ID',
        seller_id: 'Enter seller ID',
        buyer_id: 'Enter buyer ID',
        listing_id: 'Enter listing ID',
        action: 'Enter action',
        table_name: 'Enter table name',
        record_id: 'Enter record ID',
      }
      return placeholderMappings[fieldKey] || `Enter ${fieldKey}`
    }

    const isFieldRequired = (fieldKey) => {
      const requiredFields = [
        'user_id',
        'amount',
        'type',
        'status',
        'payment_method',
        'project_id',
        'verifier_id',
        'seller_id',
        'buyer_id',
        'listing_id',
        'price',
        'available_credits',
        'action',
      ]
      return requiredFields.includes(fieldKey)
    }

    const validateForm = () => {
      errors.value = {}
      let isValid = true

      requiredFields.value.forEach((field) => {
        if (field.required && (!formData.value[field.key] || formData.value[field.key] === '')) {
          errors.value[field.key] = `${field.label} is required`
          isValid = false
        }

        // Additional validation rules
        if (field.key === 'amount' && formData.value[field.key] <= 0) {
          errors.value[field.key] = 'Amount must be greater than 0'
          isValid = false
        }

        if (field.key === 'email' && formData.value[field.key]) {
          const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
          if (!emailRegex.test(formData.value[field.key])) {
            errors.value[field.key] = 'Please enter a valid email address'
            isValid = false
          }
        }
      })

      return isValid
    }

    const createRecord = async () => {
      if (!validateForm()) {
        return
      }

      creating.value = true
      try {
        // Prepare data for creation
        const recordData = { ...formData.value }

        // Add default values for certain fields
        if (props.table.name === 'wallet_accounts') {
          recordData.current_balance = recordData.current_balance || 0
          recordData.currency = recordData.currency || 'PHP'
        }

        if (props.table.name === 'wallet_transactions') {
          recordData.status = recordData.status || 'pending'
        }

        emit('save', recordData)
      } catch (error) {
        console.error('Error creating record:', error)
      } finally {
        creating.value = false
      }
    }

    const cancelCreate = () => {
      formData.value = {}
      errors.value = {}
      emit('cancel')
    }

    const initializeForm = () => {
      // Initialize form data with default values
      const defaultValues = {
        wallet_accounts: {
          current_balance: 0,
          currency: 'PHP',
        },
        wallet_transactions: {
          status: 'pending',
          type: 'deposit',
        },
        verifications: {
          status: 'pending',
        },
        listings: {
          status: 'active',
          currency: 'PHP',
        },
        orders: {
          status: 'pending',
          currency: 'PHP',
        },
        audit_logs: {
          action: 'create',
        },
      }

      formData.value = { ...defaultValues[props.table.name] } || {}
    }

    onMounted(() => {
      initializeForm()
    })

    return {
      formData,
      errors,
      creating,
      requiredFields,
      createRecord,
      cancelCreate,
    }
  },
}
</script>

<style scoped>
.record-create-form {
  max-width: 100%;
}

.create-form {
  display: flex;
  flex-direction: column;
  gap: 2rem;
}

.form-header {
  text-align: center;
  padding-bottom: 1rem;
  border-bottom: 1px solid #e2e8f0;
}

.form-header h3 {
  margin: 0 0 0.5rem 0;
  font-size: 1.5rem;
  font-weight: 600;
  color: #1a202c;
}

.form-description {
  margin: 0;
  color: #718096;
  font-size: 0.875rem;
}

.form-fields {
  display: grid;
  gap: 1.5rem;
}

.field-row {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
}

.field-label {
  font-weight: 600;
  color: #4a5568;
  font-size: 0.875rem;
  display: flex;
  align-items: center;
  gap: 0.25rem;
}

.required {
  color: #e53e3e;
  font-weight: 700;
}

.field-input {
  display: flex;
  flex-direction: column;
}

.input-field {
  padding: 0.75rem;
  border: 1px solid #e2e8f0;
  border-radius: 6px;
  font-size: 0.875rem;
  transition: border-color 0.2s;
}

.input-field:focus {
  outline: none;
  border-color: #3182ce;
  box-shadow: 0 0 0 3px rgba(49, 130, 206, 0.1);
}

.input-field.error {
  border-color: #e53e3e;
}

.input-field.error:focus {
  border-color: #e53e3e;
  box-shadow: 0 0 0 3px rgba(229, 62, 62, 0.1);
}

.textarea-field {
  resize: vertical;
  min-height: 100px;
}

.error-message {
  color: #e53e3e;
  font-size: 0.75rem;
  margin-top: 0.25rem;
}

.form-actions {
  display: flex;
  justify-content: flex-end;
  gap: 1rem;
  padding-top: 1rem;
  border-top: 1px solid #e2e8f0;
}

.loading-spinner {
  width: 1rem;
  height: 1rem;
  border: 2px solid transparent;
  border-top: 2px solid currentColor;
  border-radius: 50%;
  animation: spin 1s linear infinite;
}

@keyframes spin {
  to {
    transform: rotate(360deg);
  }
}

.btn {
  display: inline-flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.75rem 1.5rem;
  border: none;
  border-radius: 6px;
  font-size: 0.875rem;
  font-weight: 500;
  cursor: pointer;
  transition: all 0.2s;
  text-decoration: none;
}

.btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.btn-primary {
  background: #3182ce;
  color: white;
}

.btn-primary:hover:not(:disabled) {
  background: #2c5aa0;
}

.btn-secondary {
  background: #e2e8f0;
  color: #4a5568;
}

.btn-secondary:hover:not(:disabled) {
  background: #cbd5e0;
}

/* Responsive */
@media (max-width: 768px) {
  .form-actions {
    flex-direction: column;
  }

  .btn {
    justify-content: center;
  }
}
</style>
